name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: First interaction
      uses: actions/first-interaction@v1.1.0
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: {{ secrets.GITHUB_TOKEN }}
        # Comment to post on an individual's first issue
        issue-message: # optional
        # Comment to post on an individual's first pull request
        pr-message: # optional
